Guide: choosing-a-test-runner.md
vuejs-fr/vue-test-utils pull request #10
Opened 2017-10-15 17:11 UTC by Yaty

2017-10-17 10:24 UTC, MachinisteWeb requested changes
Bon boulot ! Quelques remarques !

2017-10-17 10:24 UTC, Haeresis commented on docs/en/guides/choosing-a-test-runner.md
> +Il y a un nombre conséquent de lanceurs de tests JavaScript et `vue-test-utils` marche avec tous ceux d'entre eux. `vue-test-utils` est agnostique de lanceurs de tests.
est agnostique en terme de lanceurs de test

2017-10-17 10:24 UTC, Haeresis commented on docs/en/guides/choosing-a-test-runner.md
> +Il y a tout de même plusieurs choses à considérer afin de choisir un lanceur de tests : variété des fonctionnalités, performance et support de la pré-compilation des composants monofichiers (SFC). Ap
(« SFC »)

Je suis d'avis qu'il est tellement pas populaire se terme que je sais pas s'il y a un intéret de le préciser (en général on précise ça si on traduit un terme populaire en anglais genre « end-to-end » ou « bundle » ou « SPA » mais SFC... inconnu au bataillon :D

2017-10-17 10:24 UTC, Haeresis commented on docs/en/guides/choosing-a-test-runner.md
> +- [Jest](https://facebook.github.io/jest/docs/en/getting-started.html#content) est le lanceur de test le plus complet en terme de fonctionnalités. Il requiert une configuration minimale, installe JSD
prêtes à l'utilisation

2017-10-17 10:24 UTC, Haeresis commented on docs/en/guides/choosing-a-test-runner.md
> +- [Jest](https://facebook.github.io/jest/docs/en/getting-started.html#content) est le lanceur de test le plus complet en terme de fonctionnalités. Il requiert une configuration minimale, installe JSD
dans vos test

2017-10-17 10:24 UTC, Haeresis commented on docs/en/guides/choosing-a-test-runner.md
> +Les composants Vue monofichiers (SFC) nécessites une étape de pré-compilation avant qu'ils soient lancés dans Node ou sur un navigateur. Il y a deux manières de faire qui sont recommandées pour réali
Peut être pas pertinent de garder SFC, sinon (« SFC »)

2017-10-17 10:24 UTC, Haeresis commented on docs/en/guides/choosing-a-test-runner.md
> +- [Jest](https://facebook.github.io/jest/docs/en/getting-started.html#content) est le lanceur de test le plus complet en terme de fonctionnalités. Il requiert une configuration minimale, installe JSD
préprocesseur

2017-10-20 11:05 UTC, forresst requested changes
Quelques erreurs ....

2017-10-20 11:05 UTC, forresst commented on docs/en/guides/choosing-a-test-runner.md
> +Il y a un nombre conséquent de lanceurs de tests JavaScript et `vue-test-utils` marche avec tous ceux d'entre eux. `vue-test-utils` est agnostique en termne de lanceurs de tests.
et `vue-test-utils` ~~marche~~ **fonctionne** avec tous ~~ceux d'entre eux~~.

2017-10-20 11:05 UTC, forresst commented on docs/en/guides/choosing-a-test-runner.md
> +Il y a tout de même plusieurs choses à considérer afin de choisir un lanceur de tests : variété des fonctionnalités, performance et support de la précompilation des composants monofichiers. Après avo
Après avoir ~~cautionnement~~ **soigneusement** analysé et comparé les bibliothèques,

2017-10-20 11:05 UTC, forresst commented on docs/en/guides/choosing-a-test-runner.md
> +- [Jest](https://facebook.github.io/jest/docs/en/getting-started.html#content) est le lanceur de test le plus complet en termes de fonctionnalités. Il requiert une configuration minimale, installe JS
Il n'y a cependant pas encore => Il n'a cependant pas encore

2017-10-20 11:05 UTC, forresst commented on docs/en/guides/choosing-a-test-runner.md
> +Les composants Vue monofichiers nécessites une étape de pré-compilation avant qu'ils soient lancés dans Node ou sur un navigateur. Il y a deux manières de faire qui sont recommandées pour réaliser la
nécessites => nécessitent

Il y a deux manières de faire qui sont recommandées pour réaliser la compilation : => Il existe deux méthodes recommandées pour effectuer la compilation :

2017-10-21 12:26 UTC, MachinisteWeb requested changes
Deux ajustement et ça sera bon pour moi @Yaty. Bon pour toi @forresst ?

2017-10-21 12:26 UTC, Haeresis commented on docs/en/guides/choosing-a-test-runner.md
> +Les composants Vue monofichiers nécessitent une étape de pré-compilation avant qu'ils soient lancés dans Node ou sur un navigateur. Il existe deux méthodes recommandées pour réaliser la compilation :
précompilation

2017-10-21 12:26 UTC, Haeresis commented on docs/en/guides/choosing-a-test-runner.md
> +Les composants Vue monofichiers nécessitent une étape de pré-compilation avant qu'ils soient lancés dans Node ou sur un navigateur. Il existe deux méthodes recommandées pour réaliser la compilation :
Node.js

2017-10-23 15:19 UTC, MachinisteWeb approved these changes

2017-10-23 15:19 UTC, Haeresis commented
@forresst, nous n'attendons plus que t'as bénédiction :)

2017-10-24 11:38 UTC, Haeresis commented
Tu regarderas @Yaty, il y a le nouveau fichier dom-event.md à traduire pour finaliser le guide ! C'est dans le working

2017-11-02 22:39 UTC, mdartic commented
ah désolé, je me suis permis de traduire le dom-event.md ... bon vous m'en voudrez pas hein :-)

2017-11-03 16:15 UTC, Haeresis commented
On attend toujours ta validation @forresst pour finir la partie Guide :)

2017-11-04 21:44 UTC, forresst approved these changes

2017-11-04 21:45 UTC, forresst commented
Oups ! Désolé

2017-11-05 09:36 UTC, merged