Guide: using-with-vue-router.md
vuejs-fr/vue-test-utils pull request #3
Opened 2017-10-14 21:10 UTC by Yaty

Traduction du fichier using-with-vue-router.md.
Je n'ai fait qu'une seule relecture, ça risque d'être un peu brut et pas forcement trop agréable à lire. A voir :)
J'ai un doute à la toute dernière phrase.

2017-10-15 06:41 UTC, Kocal requested changes

2017-10-15 06:41 UTC, Kocal commented on docs/en/guides/using-with-vue-router.md
> +# Utiliser avec Vue Router
> Utilisation avec

2017-10-15 06:41 UTC, Kocal commented on docs/en/guides/using-with-vue-router.md
> +Pour éviter cela, on va utiliser localVue et installer Vue Router avec.
> on peut utiliser une localVue, et installer Vue Router dessus

2017-10-15 06:41 UTC, Kocal commented on docs/en/guides/using-with-vue-router.md
> +### Utiliser stubs
> Utiliser des stubs

2017-10-15 06:41 UTC, Kocal commented on docs/en/guides/using-with-vue-router.md
> +Pour éviter cela, n'installez jamais Vue Router quand vous lancez vos tests. * TODO : est-ce que c'est vraiment le message à faire passer ? *
> Pour éviter cela, n'installez jamais Vue Router directement sur Vue mais sur localVue, lorsque vous lancez vos tests.

J'ai pas la science infuse, mais je trouve que cette phrase a déjà beaucoup + de sens que la phrase originale ^^

2017-10-15 08:52 UTC, Yaty reviewed
Merci pour la review :)

2017-10-21 12:58 UTC, MachinisteWeb requested changes
Quelques remarques. Bonne traduction comme d'hab !

2017-10-21 12:58 UTC, Haeresis commented on docs/en/guides/using-with-vue-router.md
> +Pour éviter cela, on peut utiliser une localVue, et installer Vue Router dessus.
`localVue`

2017-10-21 12:58 UTC, Haeresis commented on docs/en/guides/using-with-vue-router.md
> +On doit donc rendre ces composants vue-router disponibles au composant que nous testons. Il y a deux méthodes pour cela.
Vue Router

2017-10-21 12:58 UTC, Haeresis commented on docs/en/guides/using-with-vue-router.md
> +## Simuler `$route` and `$router`
et

2017-10-21 13:36 UTC, rspt approved these changes

2017-10-22 15:02 UTC, Kocal approved these changes

2017-10-23 15:24 UTC, MachinisteWeb approved these changes

2017-10-23 15:24 UTC, merged