Guide: testing-SFCs-with-mocha-webpack.md
vuejs-fr/vue-test-utils pull request #4
Opened 2017-10-14 21:11 UTC by Yaty

Traduction du fichier testing-SFCs-with-mocha-webpack.md
Je n'ai fait qu'une seule relecture, ça risque d'être un peu brut et pas forcement trop agréable à lire. A voir :)
Ligne 54 je n'ai pas trop su comment traduire ça (Source maps).

2017-10-15 06:59 UTC, Kocal requested changes

2017-10-15 06:59 UTC, Kocal commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +Quelques éléments importants à notés :
> à noter

2017-10-15 06:59 UTC, Kocal commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +#### Carte des sources * TODO : PAS SUR ICI *
J'ai demandé [ici](https://github.com/vuejs-fr/vuejs.org/issues/4) si on doit traduire oui ou non `source maps`

2017-10-15 06:59 UTC, Kocal commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +[Chai](http://chaijs.com/) est une bibliothèque populaire qui est généralement utiliser avec Mocha. Vous pouvez aussi jeter un coup d'œil à [Sinon](http://sinonjs.org/) pour créer des espions et des
> généralement utilisée

2017-10-15 06:59 UTC, Kocal commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
>  	  {{ count }}
`{{ compteur }}`

2017-10-17 19:40 UTC, Yaty commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +#### Carte des sources * TODO : PAS SUR ICI *
Je laisse comme ça pour le moment

2017-10-21 12:52 UTC, MachinisteWeb requested changes
Quelques changement et proposition de traduction

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +# Tester des composants monofichiers avec Mocha + Webpack
webpack

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +> Un projet exemple pour cette installation est disponible sur [GitHub](https://github.com/vuejs/vue-test-utils-mocha-webpack-example).
Un exemple de projet

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +On va supposer que vous commencez avec une installation qui a déjà webpack, vue-loader et Babel de correctement configurés (cf. le template `webpack-simple` via `vue-cli`).
« de » est en trop ici

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +- Le dernier paramètre est un glob pour indiquer les fichiers de tests à inclure dans le paquet.
On remplace tout les bundle par paquetage (avec les mot de la famille, empaquetage, désempaquetage, empaqueter, etc.). On garde plutôt le terme paquet pour « npm est un gestionnaire de paquet »

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +#### Externaliser les dépendances NPM
npm, nom de produit

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +Dans nos tests, nous allons surement importer un nombre conséquent de dépendances NPM, certaines d'entre elles n'ont pas été conçues pour une utilisation dans un navigateur et ne peuvent être empaque
npm x2

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +#### Carte des sources
Si je devais traduire source map j'utiliserais plutôt le terme de « Coordinateurs de source » car source map est un terme qui explique que le fichier en question sert à faire le lien entre une sortie produite et son origine dans une source. Par exemple le « route mapping » est souvent traduit par « concordance de route » (mais je crois pas que concordinateur soit un terme existant :D).

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +La carte des sources doit être indiquée pour être utilisée par `mocha-webpack`. La configuration recommandée est la suivante :
En partant sur coordinateur je mettrais

```
Le coordinateur de source (« Source maps »)
```

Car ce n'est pas un terme que l'on va pouvoir trouver dans un dictionnaire, il est pertinant d'indiquer l'original dans la première occurance.

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +Cela ajoute un environnement de navigateur dans node afin que `vue-test-utils` fonctionne correctement.
Node.js

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +[Chai](http://chaijs.com/) est une bibliothèque populaire qui est généralement utilisée avec Mocha. Vous pouvez aussi jeter un coup d'œil à [Sinon](http://sinonjs.org/) pour créer des espions et des
préprogrammé (« stubs »).

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +Une autre chose à noter est que si vous utilisez une version de Node >= 6, qui supporte déjà une majorité des fonctionnalités d'ES2015, vous pouvez configurer séparément un autre Babel [env option](h
Node >= 6 ---> Node.js 6+

C'est la nomonclature qu'on utlise à travers toutes les docs Vue. Si tu ne vois pas ça quelque part, tu peux PR l'originale.

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +Une autre chose à noter est que si vous utilisez une version de Node >= 6, qui supporte déjà une majorité des fonctionnalités d'ES2015, vous pouvez configurer séparément un autre Babel [env option](h
version de Node.js

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +Une autre chose à noter est que si vous utilisez une version de Node >= 6, qui supporte déjà une majorité des fonctionnalités d'ES2015, vous pouvez configurer séparément un autre Babel [env option](h
Si tu mets 

```
`stage-2`
```
je te laisse mettre 

```
`stage-x`
````
 sur l'un des précédents fichiers déjà validé

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +	  <button @click="incrementer">Incrementer</button>
`<button @click="increment">Incrementer</button>`

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +    incrementer () {
increment

2017-10-21 12:52 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +	  <button @click="incrementer">Incrementer</button>
Laisse count car ça nous fera moins de conflits à résoudre en cas de changement de code. On traduit texte, label et valeur de chaine de caractère. « increment » étant une fonction, on ne le traduit pas.

2017-10-21 13:35 UTC, rspt approved these changes

2017-10-22 15:02 UTC, Kocal approved these changes

2017-10-23 15:21 UTC, MachinisteWeb approved these changes

2017-10-23 15:21 UTC, MachinisteWeb approved these changes

2017-10-23 15:22 UTC, merged