Guide: testing-SFCs-with-jest.md
vuejs-fr/vue-test-utils pull request #5
Opened 2017-10-14 21:12 UTC by Yaty

Traduction du fichier testing-SFCs-with-jest.md
Je n'ai fait qu'une seule relecture, ça risque d'être un peu brut et pas forcement trop agréable à lire. A voir :)

2017-10-17 10:25 UTC, Haeresis commented
Je me lance. Même pas peur.

2017-10-17 10:44 UTC, MachinisteWeb requested changes
Top ! Pas mal pour une relecture censée être effrayante :D

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +> Un projet exemple pour cette installation est disponible sur [GitHub](https://github.com/vuejs/vue-test-utils-jest-example).
Un exemple de projet

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +On va supposer que vous commencez avec une installation qui a déjà webpack, vue-loader et Babel de correctement configurés (cf. le template `webpack-simple` via `vue-cli`).
remplace « e.g. » par « par ex. » chaque fois que tu le croise.
De la même manière chaque i.e. que tu croises seront des « c.-à-d. »

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +Pour indiquer à Jest comment traiter les fichiers `*.vue`, on va avoir besoin d'installer et de configurer le pré-processeur `jest-vue` :
préprocesseur

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +      // indique à Jest de gérer les fichiers *.vue
```
`*.vue`
```

Tu peux PR l'original si tu le souhaites.

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +      // traite les fichiers *.vue avec jest-vue
```
`*.vue`
```

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +> **Note :** `jest-vue` ne supporte actuellement pas toutes les fonctionnalités de `vue-loader`, par exemple le support des blocs personalisés et du chargement de styles. De plus, quelques fonctionna
spécifiques

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +> **Note :** `jest-vue` ne supporte actuellement pas toutes les fonctionnalités de `vue-loader`, par exemple le support des blocs personalisés et du chargement de styles. De plus, quelques fonctionna
code-splitting --> scission de code

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +> **Note :** `jest-vue` ne supporte actuellement pas toutes les fonctionnalités de `vue-loader`, par exemple le support des blocs personalisés et du chargement de styles. De plus, quelques fonctionna
lisez le guide pour savoir comment [tester

(histoire d'accompagner le titre)

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +Si vous utilisez un alias de résolution dans la configuration de webpack, c.à.d faire un alias `@` pour `/src`, vous devez aussi ajouter une configuration pour Jest en utilisant l'option `moduleNameM
c.-à-d.

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +    // gère le même alias dans le code @ -> src
supporte la même concordance d'alias @ -> src dans le code source

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +Même si les dernières versions de Node supportent la plupart des fonctionnalités ES2015, vous souhaitez quand même utiliser la syntaxe des modules ES ainsi que les fonctionnalités stage-x dans vos te
version de Node.js

PR l'original si tu le souhaites.

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +      // gèrer le JavaScript avec babel-jest
`babel-jest`

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +En assumant que vous utilisez `babel-preset-env` avec webpack, la configuration par défaut de Babel désactive la transpilation des modules ES car webpack sait déjà comment traiter ces modules. Nous d
En supposant

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +En assumant que vous utilisez `babel-preset-env` avec webpack, la configuration par défaut de Babel désactive la transpilation des modules ES car webpack sait déjà comment traiter ces modules. Nous d
Nous devons cependant l'activer

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +On doit aussi indiquer à `babel-preset-env` d'utiliser la version de Node que nous utilisons. Cela empêchera de transpiler inutilement des fonctionnalités et lancera nos tests plus rapidement.
Node.js

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +Exemple `.babelrc`:
espace avant le « : »

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +Vous pouvez utiliser [`vue-server-renderer`](https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer) pour transformer un composant en une chaîne de caractères afin de le sauvegarder dans
chaine (graphie rectifiée 1990)

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +Par défaut, Jest va récursivement récupérer tous les fichier qui ont une extension en `.spec.js` ou `.test.js` dans le projet. Si cela ne correspond pas à vos besoins, il est possible [de changer l'e
les fichiers

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +Par défaut, Jest va récursivement récupérer tous les fichier qui ont une extension en `.spec.js` ou `.test.js` dans le projet. Si cela ne correspond pas à vos besoins, il est possible [de changer l'e
```
`testRegex`
```

2017-10-17 10:44 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +describe('Composant', () => {
Component

2017-10-17 12:18 UTC, rspt requested changes

2017-10-17 12:18 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +> **Note :** `jest-vue` ne supporte actuellement pas toutes les fonctionnalités de `vue-loader`, par exemple le support des blocs personalisés et du chargement de styles. De plus, quelques fonctionna
"support des blocks personnalisés"

2017-10-17 12:18 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +> **Note :** `jest-vue` ne supporte actuellement pas toutes les fonctionnalités de `vue-loader`, par exemple le support des blocs personalisés et du chargement de styles. De plus, quelques fonctionna
"fonctionnalités spécifiques"

2017-10-17 12:18 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +      // gèrer le JavaScript avec babel-jest
"gérer"

2017-10-17 12:18 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +En assumant que vous utilisez `babel-preset-env` avec webpack, la configuration par défaut de Babel désactive la transpilation des modules ES car webpack sait déjà comment traiter ces modules. Nous d
"autoconfigurer"

2017-10-17 12:18 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +Pour appliquer ces options uniquement aux tests, mettez les dans un fichier de configuration différent sous `env.test` (cela va être automatiquement être utilisé par `babel-jest`).
"mettez-les"

2017-10-17 12:18 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +Puis configurez le dans `package.json`:
"configurez-le"

2017-10-17 12:18 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +    // serialiseur pour les instantanés
"sérialiseur"

2017-10-17 13:10 UTC, rspt approved these changes

2017-10-17 20:43 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +> **Note :** `jest-vue` ne supporte actuellement pas toutes les fonctionnalités de `vue-loader`, par exemple le support des blocks personnalisés et du chargement de styles. De plus, quelques fonction
"support des blocs personnalisés"

@Yaty Excuse-moi, j'ai changé par erreur le mot "bloc" dans ma première review. Je pense que c'est plus juste de laisser blocs plutôt que blocks.

2017-10-21 12:31 UTC, MachinisteWeb requested changes
Quelques éléments trouvés en plus.

2017-10-21 12:31 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +Jest est un lanceur de tests développé par Facebook. Il a pour but de procurer une solution complète de tests unitaire. Vous pouvez en apprendre plus sur Jest sur [sa documentation officielle](https:
unitaires

2017-10-21 12:31 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +On va supposer que vous commencez avec une installation qui a déjà webpack, vue-loader et Babel de correctement configurés (ex. le template `webpack-simple` via `vue-cli`).
je pense pas que le « de » soit nécessaire en fait. Il alourdi la phrase.

2017-10-21 12:31 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +> **Note :** `jest-vue` ne supporte actuellement pas toutes les fonctionnalités de `vue-loader`, par exemple le support des blocs personnalisés et du chargement de styles. De plus, quelques fonctionn
scission de code

2017-10-21 12:31 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +Même si les dernières version de Node supportent la plupart des fonctionnalités ES2015, vous souhaitez quand même utiliser la syntaxe des modules ES ainsi que les fonctionnalités stage-x dans vos tes
Node.js

2017-10-21 12:31 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +En assumant que vous utilisez `babel-preset-env` avec webpack, la configuration par défaut de Babel désactive la transpilation des modules ES car webpack sait déjà comment traiter ces modules. Nous d
En supposant

2017-10-21 12:31 UTC, Haeresis commented on docs/en/guides/testing-SFCs-with-jest.md
> +En assumant que vous utilisez `babel-preset-env` avec webpack, la configuration par défaut de Babel désactive la transpilation des modules ES car webpack sait déjà comment traiter ces modules. Nous d
Node.js

2017-10-22 15:03 UTC, Kocal approved these changes

2017-10-23 15:20 UTC, MachinisteWeb approved these changes

2017-10-23 15:20 UTC, merged