LANGS, README & SUMMARY
vuejs-fr/vue-test-utils pull request #6
Opened 2017-10-14 21:19 UTC by Yaty

2017-10-16 14:22 UTC, MachinisteWeb requested changes
Parfait ! Je vois que tu maitrises bien les terminologies française ! Bon travail ;)

2017-10-16 14:22 UTC, Haeresis commented on docs/en/README.md
> +  * [Tester des composants monofichiers avec Mocha et Webpack](guides/testing-SFCs-with-mocha-webpack.md)
webpack (sans majuscule)

2017-10-16 14:22 UTC, Haeresis commented on docs/en/SUMMARY.md
> +  * [Tester des composants monofichiers avec Mocha et Webpack](guides/testing-SFCs-with-mocha-webpack.md)
webpack

2017-10-16 14:22 UTC, Haeresis commented on docs/en/SUMMARY.md
> +  * [Options de montag](api/options.md)
montage

2017-10-16 14:22 UTC, Haeresis commented on docs/en/guides/README.md
> +* [Tester des composants monofichiers avec Mocha et Webpack](./testing-SFCs-with-mocha-webpack.md)
webpack

2017-10-16 19:42 UTC, Yaty commented
Merci c'est corrigé !

2017-10-17 09:42 UTC, MachinisteWeb approved these changes

2017-10-17 09:43 UTC, Haeresis commented
C'est bon pour moi. Je pense qu'on a pas besoin de plus d'avis pour celui-là

2017-10-17 09:44 UTC, merged