Guide: using-with-vuex.md
vuejs-fr/vue-test-utils pull request #7
Opened 2017-10-14 21:21 UTC by Yaty

Traduction du fichier using-with-vuex.md
Je n'ai fait qu'une seule relecture, ça risque d'être un peu brut et pas forcement trop agréable à lire. A voir :)
Ligne 40 : pas sûr du verbe à utiliser (j'ai laissé un TODO)

2017-10-21 13:16 UTC, MachinisteWeb requested changes
Merci pour la traduction ! Dans Vuex on a traduit state par état et getter par accesseur. Le store reste le store !

2017-10-21 13:16 UTC, MachinisteWeb commented on docs/en/guides/using-with-vuex.md
> +## Simuler des Actions
des actions

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
>  </script>
Cliquer

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +Pour tester cela, on doit passer un store fictif à Vue lorsque l'on isole notre composant. *TODO : Isoler, bon verbe ?*
Bon pour moi isole

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +Au lieu de passer le store au constructeur de base de Vue, on peut le passer à - [localVue](../api/options.md#localvue). Une localVue est un constructeur à portée limitée de Vue sur lequel on peut ef
```
le passer à [`localVue`](...
```

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +Au lieu de passer le store au constructeur de base de Vue, on peut le passer à - [localVue](../api/options.md#localvue). Une localVue est un constructeur à portée limitée de Vue sur lequel on peut ef
```
un Vue local est un constructeur
```
ou 
```
un `localVue` est un constructeur
```

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +  it('appelle une action du store (actionInput) quand la valeur de l\'input est input et qu\'un évènement input est lancée', () => {
On s'autorise le " en français dans le cas ou les « ' » sont utilisés dans la traduction

```
it("appelle l'action `actionInput` du store quand la valeur du champ est `input` et qu'un évènement `input` est lancé", () =>
```

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +  it('n\'appelle pas l\'action du store actionInput quand la valeur de l\'input n\'est pas input et qu\'un évènement input est lancée', () => {
```
it("n'appelle pas l'action `actionInput` du store quand la valeur du champ n'est pas `input` et qu'un évènement `input` est lancé", () => {
```

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +  it('appelle l\'action du store actionClick quand le bouton est cliqué', () => {
```
it("appelle l'action `actionClick` du store quand le bouton est cliqué", () => {
```

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +On utilise `beforeEach` pour s'assurer que nous avons un store propre avant chaque test. `beforeEach` est un hook de Mocha qui est appelé avant chaque test. Dans nos tests, on réassigne des valeurs a
changer l'état dans nos tests

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +La chose la plus importante à noter dans ce test est que **l'on créer une simulation d'un store Vuex, qui est ensuite passé à vue-test-utils**.
on crée

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +Génial, on peut désormais simuler des actions. Allons avoir comment simuler des getters !
Voyons comment simuler les accesseurs

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +## Simuler des Getters
Simuler des accesseurs

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +C'est un composant relativement simple. Il affiche le résultat des getters `clicks` et `inputValue`. Encore une fois, on se fiche de savoir ce que ces getters retournent. On souhaite juste savoir si
accesseurs x2

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +  it('affiche state.inputValue dans le premier tag p', () => {
```
'affiche `state.inputValue` dans la premier balise `<p>`'
```

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +  it('affiche stat.clicks dans le second tag p', () => {
```
'affiche `stat.clicks` dans le seconde balise`<p>`'
```

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +Ce test est similaire à notre test sur les actions. On créer un store fictif avant chaque test, on le passe ensuite comme une option lorsque l'on appelle `shallow`. Pour finir, on asserte que la vale
accesseurs

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +C'est génial, mais comment faisons-nous pour vérifier que nos getters retournent correctement les parties du state ?
les parties de l'état

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +## Simulation avec des Modules
avec des modules

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +[Modules](https://vuex.vuejs.org/en/modules.html) sont utiles pour séparer un store en plusieurs morceaux. Ils exportent des getters que l'on peut utiliser dans nos tests.
Les [modules]

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +[Modules](https://vuex.vuejs.org/en/modules.html) sont utiles pour séparer un store en plusieurs morceaux. Ils exportent des getters que l'on peut utiliser dans nos tests.
accesseurs

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
>  ```
Cliquer

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +Simple composant qui possède une action et un getter.
un accesseur

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +  it('appelle l\'action du store moduleActionClick quand le bouton est cliqué', () => {
```
it("appelle l'action `moduleActionClick` du store quand le bouton est cliqué", () => {
```

2017-10-21 13:16 UTC, Haeresis commented on docs/en/guides/using-with-vuex.md
> +  it('affiche state.inputValue dans le premier tag p', () => {
```
it('affiche `state.inputValue` dans la première balise `<p>`', () => {
```

2017-10-21 13:37 UTC, rspt approved these changes

2017-10-22 15:01 UTC, Kocal approved these changes

2017-10-23 15:23 UTC, MachinisteWeb approved these changes

2017-10-23 15:23 UTC, merged