Guide: getting-started.md
vuejs-fr/vue-test-utils pull request #8
Opened 2017-10-14 22:07 UTC by Yaty

Traduction du fichier getting-started.md
Je n'ai fait qu'une seule relecture, ça risque d'être un peu brut et pas forcement trop agréable à lire. A voir :)

2017-10-16 12:53 UTC, MachinisteWeb reviewed
Excellente traduction ! Mes retours !

2017-10-16 12:53 UTC, Haeresis commented on docs/en/guides/getting-started.md
> +// Importe la méthode mount() depuis test utils
`mount()`
hésite pas à PR l'originale

2017-10-16 12:53 UTC, Haeresis commented on docs/en/guides/getting-started.md
> +Les composants montés sont retournés sous un [Wrapper](./api/wrapper.md), qui expose en quantité des méthodes pour manipuler, traverser et interroger l'instance du composant Vue en question.
retournés **dans un** ?

2017-10-16 12:53 UTC, Haeresis commented on docs/en/guides/getting-started.md
> +// On accède à l'instance actuelle de Vue via wrapper.vm
`wrapper.vm`

2017-10-16 12:53 UTC, Haeresis commented on docs/en/guides/getting-started.md
> +Nous avons maintenant un wrapper, la première chose que l'on peut faire et de vérifier que le contenu du rendu HTML du composant correspond à ce qu'il est sensé être.
est de vérifier

2017-10-16 12:53 UTC, Haeresis commented on docs/en/guides/getting-started.md
> +Nous avons maintenant un wrapper, la première chose que l'on peut faire et de vérifier que le contenu du rendu HTML du composant correspond à ce qu'il est sensé être.
**censé** car peut être remplacé par « supposé »

2017-10-16 12:53 UTC, Haeresis commented on docs/en/guides/getting-started.md
> +  // c'est auss très simple de vérifier qu'un élement existe
aussi

2017-10-16 12:53 UTC, Haeresis commented on docs/en/guides/getting-started.md
> +Vue groupe les mises à jour du DOM en attentes puis les appliquent de façon asynchrone pour prévenir d'éventuel multiples rendus causé par de multiples mutations de données. C'est pourquoi en pratiqu
*causés*

2017-10-16 12:53 UTC, Haeresis commented on docs/en/guides/getting-started.md
> +Pour simplifier cela, `vue-test-utils` applique toutes les mises à jour de façon synchrone afin que vous n'ayez pas besin d'utiliser `Vue.nextTick` pour attendre des mises à jour du DOM dans vos test
*besoin*

2017-10-16 12:53 UTC, Haeresis commented on docs/en/guides/getting-started.md
> +*Note : `nextTick` est encore nécessaire quand vous souhaitez explicitement faire avancer la boucle des événements, pour des opérations telles que des fonctions de rappel ou des résolutions de promis
je mettrais *est toujours* plutôt que *est encore*.

2017-10-16 12:53 UTC, Haeresis commented on docs/en/guides/getting-started.md
> +*Note : `nextTick` est encore nécessaire quand vous souhaitez explicitement faire avancer la boucle des événements, pour des opérations telles que des fonctions de rappel ou des résolutions de promis
Au choix :)

*résolutions de promesses* (je préfère)

*résolutions de `Promise` (j'aime moins)

2017-10-16 19:45 UTC, Yaty commented on docs/en/guides/getting-started.md
> +Nous avons maintenant un wrapper, la première chose que l'on peut faire et de vérifier que le contenu du rendu HTML du composant correspond à ce qu'il est sensé être.
ouch merci elles sont pas belles !

2017-10-17 09:47 UTC, MachinisteWeb requested changes
J'en est retrouvé une :)

2017-10-17 09:47 UTC, MachinisteWeb commented on docs/en/guides/getting-started.md
> +Les composants montés sont retournés sous un [Wrapper](./api/wrapper.md), qui expose en quantité des méthodes pour manipuler, traverser et interroger l'instance du composant Vue en question.
Tu utilise un nom de titre pour justifier la majuscule à wrapper dans se cas. Comme c'est discutable (car tu ne mets pas clairement en évidence que tu te réfères au titre d'une section, même s'il y a un lien :) et donc que c'est discutable XD), je pense que le mieux est de sois écrire wrapper avec une minuscule ou alors de l'encadrer avec des ` pour faire référence à son objet.

Qu'en penses-tu ?

2017-10-17 09:47 UTC, Haeresis commented on docs/en/guides/getting-started.md
> +Vue groupe les mises à jour du DOM en attentes puis les appliquent de façon asynchrone pour prévenir d'éventuel multiples rendus causés par de multiples mutations de données. C'est pourquoi en pratiq
éventuelles

2017-10-17 11:40 UTC, forresst requested changes
Quelques erreurs et remarques

2017-10-17 11:40 UTC, forresst commented on docs/en/guides/getting-started.md
> +Pour avoir un rapide avant goût de `vue-test-utils`, clonez notre répertoire de démontration avec l'installation de base puis installez les dépendances :
démontration => démonstration

2017-10-17 11:40 UTC, forresst commented on docs/en/guides/getting-started.md
> +Les composants montés sont retournés dans un [Wrapper](./api/wrapper.md), qui expose en quantité des méthodes pour manipuler, traverser et interroger l'instance du composant Vue en question.
qui expose en quantité des méthodes => qui expose de nombreuses méthodes

2017-10-17 11:40 UTC, forresst commented on docs/en/guides/getting-started.md
> +// puis l'aventure avec vue-test-utils commence !
puis l'aventure => puis votre aventure

2017-10-17 11:40 UTC, forresst commented on docs/en/guides/getting-started.md
> +Nous avons maintenant un wrapper, la première chose que l'on peut faire est de vérifier que le contenu du rendu HTML du composant correspond à ce qu'il est censé être.
la première chose que l'on peut faire est de vérifier => la première chose que l'on peut **faire, c'est** de vérifier 



correspond à ce qu'il est censé être. => correspond à celui attendu.

2017-10-17 11:40 UTC, forresst commented on docs/en/guides/getting-started.md
> +### Simuler des interactions utilisateur
Simuler des interactions utilisateur => Simulation de l'interaction utilisateur

2017-10-17 11:40 UTC, forresst commented on docs/en/guides/getting-started.md
> +- Intégrer `vue-test-utils` dans votre projet en [choisissant votre lanceur de tests](./choosing-a-test-runner.md)
Intégrer => Intégrez

2017-10-17 12:14 UTC, rspt requested changes

2017-10-17 12:14 UTC, rspt commented on docs/en/guides/getting-started.md
> +Pour avoir un rapide avant goût de `vue-test-utils`, clonez notre répertoire de démontration avec l'installation de base puis installez les dépendances :
"avant-gout" -> graphie rectifiée

2017-10-17 12:14 UTC, rspt commented on docs/en/guides/getting-started.md
> +  // c'est aussi très simple de vérifier qu'un élement existe
"élément"

2017-10-17 12:14 UTC, rspt commented on docs/en/guides/getting-started.md
> +Vue groupe les mises à jour du DOM en attentes puis les appliquent de façon asynchrone pour prévenir d'éventuel multiples rendus causés par de multiples mutations de données. C'est pourquoi en pratiq
@Haeresis & @forresst 

C'est pas "d'éventuels"?

2017-10-17 20:39 UTC, rspt requested changes

2017-10-17 20:39 UTC, rspt commented on docs/en/guides/getting-started.md
> +Pour avoir un rapide avant-goût de `vue-test-utils`, clonez notre répertoire de démonstration avec l'installation de base puis installez les dépendances :
"avant-gout" -> graphie rectifiée

2017-10-18 22:19 UTC, rspt approved these changes

2017-10-19 01:06 UTC, forresst approved these changes

2017-10-21 12:19 UTC, MachinisteWeb approved these changes

2017-10-21 12:19 UTC, merged