Guide: common-tips.md
vuejs-fr/vue-test-utils pull request #9
Opened 2017-10-15 17:08 UTC by Yaty

2017-10-16 14:19 UTC, MachinisteWeb requested changes
Globalement je vois que tu as pris le parti de tout traduire (même les nom de variable) dans cette traduction alors que tu ne l'avais pas fait pour le fichier `get-started.md`

Personnellement je préfère ne traduire que les valeurs de variable et commentaire et pas les noms de variables mais ceci est uniquement basé sur mon opinion. Je ne vois donc pas d'objection à ce que les noms de variables et fonction soit aussi en français pour aider le lecteur.

Il faut juste que tu fasses un choix et que tu t'y tienne à travers toute la traduction !

Pour infos voici ce qui as déjà été fait : 

- vuejs.org guide (juste contenu et commentaire en français)
- vuejs.org API (tout traduit)
- vuex (juste contenu et commentaire en français)
- vue-router (juste contenu et commentaire en français)
- vue-ssr-docs (juste contenu et commentaire en français)
- nuxt (juste contenu et commentaire en français)

Toi qui voit !

2017-10-16 14:19 UTC, MachinisteWeb commented on docs/en/guides/common-tips.md
> +Par exemple, pour le composant `Compteur`, qui incrémente un compteur visible par un à chaque fois qu'un bouton est cliqué, le scénario de test devrait simuler le clic puis s'assurer que le rendu vis
un compteur visible **de 1**

2017-10-16 14:19 UTC, MachinisteWeb commented on docs/en/guides/common-tips.md
> +A contrario, nous recommandons d'écrire des tests qui vérifie le bon fonctionnement de l'interface publique de vos composants et ainsi traiter le cœur de ceux-ci telle une boîte noire. Un simple test
vérifient

2017-10-16 14:19 UTC, MachinisteWeb commented on docs/en/guides/common-tips.md
> +A contrario, nous recommandons d'écrire des tests qui vérifie le bon fonctionnement de l'interface publique de vos composants et ainsi traiter le cœur de ceux-ci telle une boîte noire. Un simple test
interface public (ici public est un adjectif)

2017-10-16 14:19 UTC, MachinisteWeb commented on docs/en/guides/common-tips.md
> +A contrario, nous recommandons d'écrire des tests qui vérifie le bon fonctionnement de l'interface publique de vos composants et ainsi traiter le cœur de ceux-ci telle une boîte noire. Un simple test
dûe (car il me semble que « dû » fait référence à l'entrée utilisateur passée au composant et non pas au test)

2017-10-16 14:19 UTC, MachinisteWeb commented on docs/en/guides/common-tips.md
> +A contrario, nous recommandons d'écrire des tests qui vérifie le bon fonctionnement de l'interface publique de vos composants et ainsi traiter le cœur de ceux-ci telle une boîte noire. Un simple test
(cela peut être un nouveau rendu ou l'envoi d'un évènement)

2017-10-16 14:19 UTC, MachinisteWeb commented on docs/en/guides/common-tips.md
> +Par exemple, pour le composant `Compteur`, qui incrémente un compteur visible par un à chaque fois qu'un bouton est cliqué, le scénario de test devrait simuler le clic puis s'assurer que le rendu vis
```
Par exemple, pour le composant `Counter`
```
Pour rester consistant avec `get-started.md` qui traduit uniquement les valeur de chaine de caractère et les commentaires (pas les nom de fichier, pas les nom de fonction, pas les objets, etc.)

```
(du résultat)
```
pour rester cohérant avec `de` l'entrée et `de` la sortie

2017-10-16 14:19 UTC, MachinisteWeb commented on docs/en/guides/common-tips.md
> +Par exemple, pour le composant `Compteur`, qui incrémente un compteur visible par un à chaque fois qu'un bouton est cliqué, le scénario de test devrait simuler le clic puis s'assurer que le rendu vis
```
se fiche de savoir comment le compteur
```
pas de majuscule à compteur, je rajouterais « de savoir »

2017-10-16 14:19 UTC, MachinisteWeb commented on docs/en/guides/common-tips.md
> +Le bénéfice de cette approche est que tant que l'interface publique de votre composant reste la même, vos tests passeront et ce peu importe le comportement interne de votre composant, qui pourrait ch
interface public

2017-10-16 14:19 UTC, MachinisteWeb commented on docs/en/guides/common-tips.md
> +const wrapper = shallow(Composant) // retourne un Wrapper contenant une instance de Composant montée
composant sans majuscule, wrapper sans majuscule

2017-10-16 14:19 UTC, MachinisteWeb commented on docs/en/guides/common-tips.md
> +const wrapper = shallow(Composant) // retourne un Wrapper contenant une instance de Composant montée
> Tu n'as pas traduis « Counter » dans le Get Started, tu ne devrais donc pas traduire `Component` ici

2017-10-16 14:19 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +wrapper.emitted() retourne l'objet suivant :
```
`wrapper.emitted()` retourne l'objet suivant :
```

2017-10-16 14:19 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +## Affirmer l'émission d'événements
Tu peux mettre 
```
Assertion d'évènements émis
```
Pour être consistant avec le propos

2017-10-16 14:19 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +Chaque wrapper monté va automatiquement enregistrer les événements émis par l'instance de Vue en question. Vous pouvez récupérer ces événements en utilisant la méthode `wrapper.emitted()` :
évènement (on utilise la graphie rectifié post 1990) (fait un remplacement pour tous les terme événement vers évènement)

2017-10-16 14:19 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +Vous pouvez aussi récupérer un tableau des événements dans l'ordre d'émition en appelant [wrapper.emittedByOrder()](../api/wrapper/emittedByOrder.md).
```
en appelant [`wrapper.emittedByOrder()`](../api/wrapper/emittedByOrder.md)
```

2017-10-16 14:19 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +wrapper.setData({ compteur: 10 })
Ne pas traduire `count` (ou alors traduire tout ce qui doit être traduit dans le Get Started)

2017-10-16 14:19 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +mount(Composant, {
Garder `Component` si pas de traduction de get-started.md

2017-10-16 14:19 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +Si vous écrivez des tests pour des composants dans une application spécifique, vous pouvez mettre en place les mêmes plugins globaux et mixins en une seule fois dans vos tests. Dans certains cas, com
```
 [`createLocalVue`](../api/createLocalVue.md)
```

Tu peux PR l'original chaque fois que tu utilises des ` qu'il n'ont pas mis.

2017-10-16 14:19 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +localVue.use(MonPlugin)
Garder MyPlugin (ou traduire get-started.md)

2017-10-16 14:19 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +// passe la localVue aux options de montage
```
`localVue`
```

2017-10-16 14:19 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +mount(Composant, {
Garder `Component` ou traduire le get-started.md (pensez à `counter.js` qui deviendra `compteur.js`)

2017-10-16 14:19 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +Depuis que le routage, par définition, porte sur la structure générale de l'application et implique plusieurs composants. Il est mieux testé via des tests d'intégration ou end-to-end. Pour des compos
ou point à point (déjà utilisé pour end-to-end dans une traduction Nuxt).

2017-10-16 20:03 UTC, Yaty commented
Ok merci pour la review, du coup je pars sur traduire uniquement le contenu et les commentaires histoire d'uniformiser ça.
Je viens de voir que cette PR est complètement pété, je la referai avant le merge :)

2017-10-17 09:49 UTC, Haeresis commented
J'ai résolu les conflis, pense à pull chez toi avant de continuer la review :)

2017-10-17 10:02 UTC, Haeresis commented
Ok, je m'occupe que du fichier common-tip

2017-10-17 10:13 UTC, MachinisteWeb requested changes
Petite bavure avec de bout en bout :D

2017-10-17 10:13 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +Depuis que le routage, par définition, porte sur la structure générale de l'application et implique plusieurs composants. Il est mieux testé via des tests d'intégration ou point à point (end-to-end).
« end-to-end » pour rester consistant avec les autres docs.

Et je t'ai dit des conneries, c'est de « bout en bout » : https://fr.nuxtjs.org/guide/development-tools/

Vraiment désolé :(

2017-10-17 10:14 UTC, Haeresis commented
Je continue en partant du postulat commentaire et valeur :)

2017-10-17 12:11 UTC, rspt requested changes

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/choosing-a-test-runner.md
> +Un lanceur de tests est un programme qui lance des tests (et oui !).
On écrit "eh oui !". C'est une interjection :)

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/choosing-a-test-runner.md
> +Il y a tout de même plusieurs choses à considérer afin de choisir un lanceur de tests : variété des fonctionnalités, performance et support de la pré-compilation des composants monofichiers (SFC). Ap
"précompilation"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/choosing-a-test-runner.md
> +- [Jest](https://facebook.github.io/jest/docs/en/getting-started.html#content) est le lanceur de test le plus complet en terme de fonctionnalités. Il requiert une configuration minimale, installe JSD
"en termes"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/choosing-a-test-runner.md
> +- [Jest](https://facebook.github.io/jest/docs/en/getting-started.html#content) est le lanceur de test le plus complet en terme de fonctionnalités. Il requiert une configuration minimale, installe JSD
"préprocesseur"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/choosing-a-test-runner.md
> +`vue-test-utils` se fie à un environnement de navigateur. Techniquement, vous pouvez le lancer dans un vrai navigateur, mais cela n'est pas recommandé dû à la complexité de lancer de réels navigateur
"de réels navigateurs"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/common-tips.md
> +A contrario, nous recommandons d'écrire des tests qui vérifient le bon fonctionnement de l'interface public de vos composants et ainsi traiter le cœur de ceux-ci telle une boîte noire. Un simple test
"À contrario"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/common-tips.md
> +A contrario, nous recommandons d'écrire des tests qui vérifient le bon fonctionnement de l'interface public de vos composants et ainsi traiter le cœur de ceux-ci telle une boîte noire. Un simple test
"boite" (graphie rectifiée)

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/common-tips.md
> +Le bénéfice de cette approche est que tant que l'interface public de votre composant reste la même, vos tests passeront et ce peu importe le comportement interne de votre composant, qui pourrait chan
"interface publique"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/common-tips.md
> +Ce sujet est discuté plus en détails dans une [très bonne présentation de Matt O'Connell](http://slides.com/mattoconnell/deck#/).
"en détail" -> invariable

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/common-tips.md
> +Vous pouvez aussi récupérer un tableau des évènements dans l'ordre d'émition en appelant [`wrapper.emittedByOrder()`](../api/wrapper/emittedByOrder.md).
"émission"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/common-tips.md
> +Depuis que le routage, par définition, porte sur la structure générale de l'application et implique plusieurs composants. Il est mieux testé via des tests d'intégration ou point à point (end-to-end).
"qui se fient"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/getting-started.md
> +Pour avoir un rapide avant goût de `vue-test-utils`, clonez notre répertoire de démontration avec l'installation de base puis installez les dépendances :
"avant-gout" -> graphie rectifiée

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/getting-started.md
> +Pour avoir un rapide avant goût de `vue-test-utils`, clonez notre répertoire de démontration avec l'installation de base puis installez les dépendances :
"démonstration"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/getting-started.md
> +`vue-test-utils` teste les composants Vue en les isolants puis en les montant, il simule les entrées nécessaires (props, injections et événements utilisateur) et asserte les sorties (le rendu, les év
"évènements" -> graphie rectifiée

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/getting-started.md
> +*Note : `nextTick` est encore nécessaire quand vous souhaitez explicitement faire avancer la boucle des événements, pour des opérations telles que des fonctions de rappel ou des résolutions de promis
"évènements" -> graphie rectifiée

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/getting-started.md
> +  // c'est auss très simple de vérifier qu'un élement existe
"aussi"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/getting-started.md
> +  // c'est auss très simple de vérifier qu'un élement existe
"élément"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/getting-started.md
> +Vue groupe les mises à jour du DOM en attentes puis les appliquent de façon asynchrone pour prévenir d'éventuel multiples rendus causé par de multiples mutations de données. C'est pourquoi en pratiqu
"d'éventuels"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/getting-started.md
> +Vue groupe les mises à jour du DOM en attentes puis les appliquent de façon asynchrone pour prévenir d'éventuel multiples rendus causé par de multiples mutations de données. C'est pourquoi en pratiqu
"causés"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/getting-started.md
> +Pour simplifier cela, `vue-test-utils` applique toutes les mises à jour de façon synchrone afin que vous n'ayez pas besin d'utiliser `Vue.nextTick` pour attendre des mises à jour du DOM dans vos test
"besoin"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +Pour indiquer à Jest comment traiter les fichiers `*.vue`, on va avoir besoin d'installer et de configurer le pré-processeur `jest-vue` :
"préprocesseur"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +> **Note :** `jest-vue` ne supporte actuellement pas toutes les fonctionnalités de `vue-loader`, par exemple le support des blocs personalisés et du chargement de styles. De plus, quelques fonctionna
"personnalisés"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +> **Note :** `jest-vue` ne supporte actuellement pas toutes les fonctionnalités de `vue-loader`, par exemple le support des blocs personalisés et du chargement de styles. De plus, quelques fonctionna
"spécifiques"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +Si vous utilisez un alias de résolution dans la configuration de webpack, c.à.d faire un alias `@` pour `/src`, vous devez aussi ajouter une configuration pour Jest en utilisant l'option `moduleNameM
"c.-à-d."

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +      // gèrer le JavaScript avec babel-jest
"gérer"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +> Par défaut, `babel-jest` va automatiquement s'auto-configurer dès l'installation. Cependant, comme nous avons explicitement ajouté une transformation pour les fichiers `*.vue`, on se doit aussi d'e
"s'autoconfigurer"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +Pour appliquer ces options uniquement aux tests, mettez les dans un fichier de configuration différent sous `env.test` (cela va être automatiquement être utilisé par `babel-jest`).
"mettez-les"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +Vous pouvez utiliser [`vue-server-renderer`](https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer) pour transformer un composant en une chaîne de caractères afin de le sauvegarder dans
"chaine" -> graphie rectifiée

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +Puis configurez le dans `package.json`:
"configurez-le"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +    // serialiseur pour les instantanés
"sérialiseur"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-jest.md
> +Par défaut, Jest va récursivement récupérer tous les fichier qui ont une extension en `.spec.js` ou `.test.js` dans le projet. Si cela ne correspond pas à vos besoins, il est possible [de changer l'e
"tous les fichiers"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +- Le paramètre `--require` permet de s'assurer que le fichier `test/setup.js` est bien exécuté avant les tests. Dans celui-ci, on met en place l'environnement où nos tests vont être éxécutés.
"vont être exécutés"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +Dans nos tests, nous allons sûrement importer un nombre conséquent de dépendances NPM, certaines d'entre-elles n'ont pas été conçues pour une utilisation dans un navigateur et ne peuvent être empaque
"surement" -> graphie rectifiée

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +Dans nos tests, nous allons sûrement importer un nombre conséquent de dépendances NPM, certaines d'entre-elles n'ont pas été conçues pour une utilisation dans un navigateur et ne peuvent être empaque
"certaines d'entre elles"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +Si vous déboguer via votre IDE, il est recommandé d'ajouter la configuration suivante :
"vous déboguez"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/testing-SFCs-with-mocha-webpack.md
> +Une autre chose à noter est que si vous utilisez une version de Node >= 6, qui supporte déjà une majorité des fonctionnalités d'ES2015, vous pouvez configurer séparément un autre Babel [env option](h
"c.-à-d."

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/using-with-vuex.md
> +On va ensuite créer un store fictif en appelant `new Vuex.Store` avec nos propres valeurs. À noté que l'on indique uniquement nos actions, car on ne s'intéresse qu'à elles.
À noter

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/using-with-vuex.md
> +Les actions sont des [fonctions de simulations de Jest](https://facebook.github.io/jest/docs/en/mock-functions.html). Ces fonctions nous donnent accès à des méthodes afin de réaliser des assertions s
"l'action a été"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/using-with-vuex.md
> +La manière dont on définit le store peut vous paraître un peu étrange.
"paraitre" -> graphie rectifiée

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/using-with-vuex.md
> +La chose la plus importante à noter dans ce test est que **l'on créer une simulation d'un store Vuex, qui est ensuite passer à vue-test-utils**.
"qui est ensuite passé"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/using-with-vuex.md
> +Ce test est similaire à notre test sur les actions. On créer un store fictif avant chaque test, on le passe ensuite comme une option lorsque l'on appele `shallow`. Pour finir, on asserte que la valeu
"appelle"

2017-10-17 12:11 UTC, rspt commented on docs/en/guides/using-with-vuex.md
> +C'est génial, mais comment faisons nous pour vérifier que nos getters retournent correctement les parties du state ?
"faisons-nous"

2017-10-17 13:07 UTC, Yaty commented
Je corrige ça dans la soirée. Je répète j'ai foiré la PR, celle-ci ne concerne que common-tips.md. Je prends quand même tes corrections qui vont être faites sur les PR correspondantes :)

2017-10-17 13:13 UTC, rspt commented
> Je corrige ça dans la soirée. Je répète j'ai foiré la PR, celle-ci ne concerne que common-tips.md. Je prends quand même tes corrections qui vont être faites sur les PR correspondantes :)

@Yaty Ah oui excuse-moi, j'ai raté ce commentaire :)

Du coup tu as quand même mes suggestions pour les autres PR (je repasse volontiers sur les autres quand elles sont là)!

2017-10-17 19:53 UTC, Yaty commented on docs/en/guides/common-tips.md
> +Le bénéfice de cette approche est que tant que l'interface public de votre composant reste la même, vos tests passeront et ce peu importe le comportement interne de votre composant, qui pourrait chan
@Haeresis il y a contradiction ! public ou publique ahah ?

2017-10-17 20:14 UTC, Yaty commented
@rspt ok les PR sont corrigées !

2017-10-17 20:48 UTC, rspt commented on docs/en/guides/common-tips.md
> +Le bénéfice de cette approche est que tant que l'interface public de votre composant reste la même, vos tests passeront et ce peu importe le comportement interne de votre composant, qui pourrait chan
Je mettrai "interface publique" partout comme interface est féminin et que l'adjectif s'accorde. Pareil pour plus haut dans le texte que je n'ai pas relevé ^^

2017-10-21 12:21 UTC, Haeresis commented on docs/en/guides/common-tips.md
> +Le bénéfice de cette approche est que tant que l'interface public de votre composant reste la même, vos tests passeront et ce peu importe le comportement interne de votre composant, qui pourrait chan
Je n'avais pas réfléchi au fait que « publique » était le féminin de « public ». J'étais resté sur le fait que publique était un nom et public un adjectif. Ma faute (que je ne ferrais plus :)

2017-10-21 12:22 UTC, Haeresis commented
On te laisse résoudre le conflit @Yaty pour passer ta PR ou en soumettre une autre avec seulement le bon fichier corrigé proposé ;)

2017-10-21 17:16 UTC, closed without merging

2017-10-21 17:18 UTC, Yaty commented
https://github.com/vuejs-fr/vue-test-utils/pull/18